// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

/**
 * Protobuf enum {@code CommandRequestType}
 */
public enum CommandRequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GET = 0;</code>
   */
  GET(0),
  /**
   * <code>PUT = 1;</code>
   */
  PUT(1),
  /**
   * <code>DELETE = 2;</code>
   */
  DELETE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GET = 0;</code>
   */
  public static final int GET_VALUE = 0;
  /**
   * <code>PUT = 1;</code>
   */
  public static final int PUT_VALUE = 1;
  /**
   * <code>DELETE = 2;</code>
   */
  public static final int DELETE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommandRequestType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CommandRequestType forNumber(int value) {
    switch (value) {
      case 0: return GET;
      case 1: return PUT;
      case 2: return DELETE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommandRequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommandRequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommandRequestType>() {
          public CommandRequestType findValueByNumber(int number) {
            return CommandRequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rs.raf.grpc.Storage.getDescriptor().getEnumTypes().get(0);
  }

  private static final CommandRequestType[] VALUES = values();

  public static CommandRequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CommandRequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:CommandRequestType)
}

