// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

public interface CommandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CommandRequestType op_type = 1;</code>
   * @return The enum numeric value on the wire for opType.
   */
  int getOpTypeValue();
  /**
   * <code>.CommandRequestType op_type = 1;</code>
   * @return The opType.
   */
  rs.raf.grpc.CommandRequestType getOpType();

  /**
   * <code>int32 request_id = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>string key = 3;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 4;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
