// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

public interface LeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderRequest)
    com.google.protobuf.MessageOrBuilder {
}
