// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

public interface LeaderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool imLeader = 1;</code>
   * @return The imLeader.
   */
  boolean getImLeader();

  /**
   * <code>bytes connection = 2;</code>
   * @return The connection.
   */
  com.google.protobuf.ByteString getConnection();
}
