// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

public interface LogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LogStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.LogStatus status = 1;</code>
   * @return The status.
   */
  rs.raf.grpc.LogStatus getStatus();

  /**
   * <code>uint64 entryAtIndex = 2;</code>
   * @return The entryAtIndex.
   */
  long getEntryAtIndex();

  /**
   * <code>uint64 lastEntryIndex = 3;</code>
   * @return The lastEntryIndex.
   */
  long getLastEntryIndex();
}
