// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

/**
 * Protobuf enum {@code LogStatus}
 */
public enum LogStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOG_OK = 0;</code>
   */
  LOG_OK(0),
  /**
   * <code>IO_ERROR = 1;</code>
   */
  IO_ERROR(1),
  /**
   * <code>LOG_NO_LAST_ENTRY = 2;</code>
   */
  LOG_NO_LAST_ENTRY(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LOG_OK = 0;</code>
   */
  public static final int LOG_OK_VALUE = 0;
  /**
   * <code>IO_ERROR = 1;</code>
   */
  public static final int IO_ERROR_VALUE = 1;
  /**
   * <code>LOG_NO_LAST_ENTRY = 2;</code>
   */
  public static final int LOG_NO_LAST_ENTRY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LogStatus forNumber(int value) {
    switch (value) {
      case 0: return LOG_OK;
      case 1: return IO_ERROR;
      case 2: return LOG_NO_LAST_ENTRY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogStatus>() {
          public LogStatus findValueByNumber(int number) {
            return LogStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rs.raf.grpc.Storage.getDescriptor().getEnumTypes().get(2);
  }

  private static final LogStatus[] VALUES = values();

  public static LogStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LogStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LogStatus)
}

