// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

/**
 * Protobuf service {@code StorageService}
 */
public  abstract class StorageService
    implements com.google.protobuf.Service {
  protected StorageService() {}

  public interface Interface {
    /**
     * <code>rpc SendCommand(.CommandRequest) returns (.CommandResponse);</code>
     */
    public abstract void sendCommand(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.CommandRequest request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.CommandResponse> done);

    /**
     * <code>rpc AppendLog(.LogEntry) returns (.LogResponse);</code>
     */
    public abstract void appendLog(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LogEntry request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.LogResponse> done);

    /**
     * <code>rpc GetLeaderInfo(.LeaderRequest) returns (.LeaderInfo);</code>
     */
    public abstract void getLeaderInfo(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LeaderRequest request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.LeaderInfo> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new StorageService() {
      @java.lang.Override
      public  void sendCommand(
          com.google.protobuf.RpcController controller,
          rs.raf.grpc.CommandRequest request,
          com.google.protobuf.RpcCallback<rs.raf.grpc.CommandResponse> done) {
        impl.sendCommand(controller, request, done);
      }

      @java.lang.Override
      public  void appendLog(
          com.google.protobuf.RpcController controller,
          rs.raf.grpc.LogEntry request,
          com.google.protobuf.RpcCallback<rs.raf.grpc.LogResponse> done) {
        impl.appendLog(controller, request, done);
      }

      @java.lang.Override
      public  void getLeaderInfo(
          com.google.protobuf.RpcController controller,
          rs.raf.grpc.LeaderRequest request,
          com.google.protobuf.RpcCallback<rs.raf.grpc.LeaderInfo> done) {
        impl.getLeaderInfo(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sendCommand(controller, (rs.raf.grpc.CommandRequest)request);
          case 1:
            return impl.appendLog(controller, (rs.raf.grpc.LogEntry)request);
          case 2:
            return impl.getLeaderInfo(controller, (rs.raf.grpc.LeaderRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return rs.raf.grpc.CommandRequest.getDefaultInstance();
          case 1:
            return rs.raf.grpc.LogEntry.getDefaultInstance();
          case 2:
            return rs.raf.grpc.LeaderRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return rs.raf.grpc.CommandResponse.getDefaultInstance();
          case 1:
            return rs.raf.grpc.LogResponse.getDefaultInstance();
          case 2:
            return rs.raf.grpc.LeaderInfo.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc SendCommand(.CommandRequest) returns (.CommandResponse);</code>
   */
  public abstract void sendCommand(
      com.google.protobuf.RpcController controller,
      rs.raf.grpc.CommandRequest request,
      com.google.protobuf.RpcCallback<rs.raf.grpc.CommandResponse> done);

  /**
   * <code>rpc AppendLog(.LogEntry) returns (.LogResponse);</code>
   */
  public abstract void appendLog(
      com.google.protobuf.RpcController controller,
      rs.raf.grpc.LogEntry request,
      com.google.protobuf.RpcCallback<rs.raf.grpc.LogResponse> done);

  /**
   * <code>rpc GetLeaderInfo(.LeaderRequest) returns (.LeaderInfo);</code>
   */
  public abstract void getLeaderInfo(
      com.google.protobuf.RpcController controller,
      rs.raf.grpc.LeaderRequest request,
      com.google.protobuf.RpcCallback<rs.raf.grpc.LeaderInfo> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return rs.raf.grpc.Storage.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sendCommand(controller, (rs.raf.grpc.CommandRequest)request,
          com.google.protobuf.RpcUtil.<rs.raf.grpc.CommandResponse>specializeCallback(
            done));
        return;
      case 1:
        this.appendLog(controller, (rs.raf.grpc.LogEntry)request,
          com.google.protobuf.RpcUtil.<rs.raf.grpc.LogResponse>specializeCallback(
            done));
        return;
      case 2:
        this.getLeaderInfo(controller, (rs.raf.grpc.LeaderRequest)request,
          com.google.protobuf.RpcUtil.<rs.raf.grpc.LeaderInfo>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return rs.raf.grpc.CommandRequest.getDefaultInstance();
      case 1:
        return rs.raf.grpc.LogEntry.getDefaultInstance();
      case 2:
        return rs.raf.grpc.LeaderRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return rs.raf.grpc.CommandResponse.getDefaultInstance();
      case 1:
        return rs.raf.grpc.LogResponse.getDefaultInstance();
      case 2:
        return rs.raf.grpc.LeaderInfo.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends rs.raf.grpc.StorageService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sendCommand(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.CommandRequest request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.CommandResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        rs.raf.grpc.CommandResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          rs.raf.grpc.CommandResponse.class,
          rs.raf.grpc.CommandResponse.getDefaultInstance()));
    }

    public  void appendLog(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LogEntry request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.LogResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        rs.raf.grpc.LogResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          rs.raf.grpc.LogResponse.class,
          rs.raf.grpc.LogResponse.getDefaultInstance()));
    }

    public  void getLeaderInfo(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LeaderRequest request,
        com.google.protobuf.RpcCallback<rs.raf.grpc.LeaderInfo> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        rs.raf.grpc.LeaderInfo.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          rs.raf.grpc.LeaderInfo.class,
          rs.raf.grpc.LeaderInfo.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public rs.raf.grpc.CommandResponse sendCommand(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.CommandRequest request)
        throws com.google.protobuf.ServiceException;

    public rs.raf.grpc.LogResponse appendLog(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LogEntry request)
        throws com.google.protobuf.ServiceException;

    public rs.raf.grpc.LeaderInfo getLeaderInfo(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LeaderRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public rs.raf.grpc.CommandResponse sendCommand(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.CommandRequest request)
        throws com.google.protobuf.ServiceException {
      return (rs.raf.grpc.CommandResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        rs.raf.grpc.CommandResponse.getDefaultInstance());
    }


    public rs.raf.grpc.LogResponse appendLog(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LogEntry request)
        throws com.google.protobuf.ServiceException {
      return (rs.raf.grpc.LogResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        rs.raf.grpc.LogResponse.getDefaultInstance());
    }


    public rs.raf.grpc.LeaderInfo getLeaderInfo(
        com.google.protobuf.RpcController controller,
        rs.raf.grpc.LeaderRequest request)
        throws com.google.protobuf.ServiceException {
      return (rs.raf.grpc.LeaderInfo) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        rs.raf.grpc.LeaderInfo.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:StorageService)
}

