// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package rs.raf.grpc;

public final class Storage {
  private Storage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstorage.proto\"f\n\016CommandRequest\022$\n\007op_" +
      "type\030\001 \001(\0162\023.CommandRequestType\022\022\n\nreque" +
      "st_id\030\002 \001(\005\022\013\n\003key\030\003 \001(\t\022\r\n\005value\030\004 \001(\t\"" +
      "a\n\017CommandResponse\022\036\n\006status\030\001 \001(\0162\016.Req" +
      "uestStatus\022\022\n\nrequest_id\030\002 \001(\005\022\013\n\003key\030\003 " +
      "\001(\t\022\r\n\005value\030\004 \001(\t\"6\n\010LogEntry\022\024\n\014entryA" +
      "tIndex\030\001 \001(\004\022\024\n\014logEntryData\030\002 \001(\014\"W\n\013Lo" +
      "gResponse\022\032\n\006status\030\001 \001(\0162\n.LogStatus\022\024\n" +
      "\014entryAtIndex\030\002 \001(\004\022\026\n\016lastEntryIndex\030\003 " +
      "\001(\004\"\017\n\rLeaderRequest\"2\n\nLeaderInfo\022\020\n\010im" +
      "Leader\030\001 \001(\010\022\022\n\nconnection\030\002 \001(\014*2\n\022Comm" +
      "andRequestType\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\022\n\n\006DELE" +
      "TE\020\002*[\n\rRequestStatus\022\r\n\tSTATUS_OK\020\000\022\036\n\032" +
      "UPDATE_REJECTED_NOT_LEADER\020\001\022\033\n\027VALUE_FO" +
      "R_KEY_NOT_FOUND\020\002*<\n\tLogStatus\022\n\n\006LOG_OK" +
      "\020\000\022\014\n\010IO_ERROR\020\001\022\025\n\021LOG_NO_LAST_ENTRY\020\0022" +
      "\234\001\n\016StorageService\0222\n\013SendCommand\022\017.Comm" +
      "andRequest\032\020.CommandResponse\"\000\022&\n\tAppend" +
      "Log\022\t.LogEntry\032\014.LogResponse\"\000\022.\n\rGetLea" +
      "derInfo\022\016.LeaderRequest\032\013.LeaderInfo\"\000B\022" +
      "\n\013rs.raf.grpcP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandRequest_descriptor,
        new java.lang.String[] { "OpType", "RequestId", "Key", "Value", });
    internal_static_CommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandResponse_descriptor,
        new java.lang.String[] { "Status", "RequestId", "Key", "Value", });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "EntryAtIndex", "LogEntryData", });
    internal_static_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogResponse_descriptor,
        new java.lang.String[] { "Status", "EntryAtIndex", "LastEntryIndex", });
    internal_static_LeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderRequest_descriptor,
        new java.lang.String[] { });
    internal_static_LeaderInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LeaderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderInfo_descriptor,
        new java.lang.String[] { "ImLeader", "Connection", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
